title: Volkswagen Golf
descripction:
theme: just-the-docs 
url: https://garquimig.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_external_links:
   - title: GENERACIONES
     url: https://www.youtube.com/watch?v=VYw684LCq1w&t=863s
     hide_icon: false
     opens_in_new_tab: true


favicon: "favicon.ico"
